name: healco
description: Aplikasi Deteksi Penyakit Daun Jagung
publish_to: 'none'
version: 1.0.0+1
metadata:
  author: Hanifan Husein Isnanto

environment:
  sdk: '>=2.18.6 <3.7.9'

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dart_jsonwebtoken: ^2.6.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  http: ^0.13.5
  image_picker: ^0.8.6
  intl: ^0.18.0
  launch_review: ^3.0.1
  path: ^1.8.2
  provider: ^6.0.5
  readmore: ^2.2.0
  scanning_effect: ^1.0.4
  share_plus: ^6.3.1
  shared_preferences: ^2.0.16
  sqflite: ^2.2.8+2
  url_launcher: ^6.1.7

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ic_launcher.png"

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  fonts:

    - family: AlbertSans
      fonts:
        - asset: assets/fonts/AlbertSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/AlbertSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/AlbertSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/AlbertSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/AlbertSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/AlbertSans-Light.ttf
          weight: 300
